### PR TITLE
Fixed: User is not able to update his about me section in his profile

### PR DESCRIPTION
**Pull request by maniyaom**
#235 

https://github.com/Ijaiswalshivam/Talk-In/assets/105499099/bbcc0e70-4cbd-4c26-91af-d192a47aab85

### CODE REVIEW

**Comment by Ijaiswalshivam** [comment]
@maniyaom I think you have changed the profile picture button, so please fix it.

**Comment by maniyaom** [comment]
@Ijaiswalshivam please merge it

**Comment by maniyaom** [comment]
> @maniyaom I think you have changed the profile picture button, so please fix it.

No I haven't changed it. But size of the original image is small that's why it is showing like this.

**Comment by Ijaiswalshivam** [comment]
Ok... I'll see it.

**Comment by maniyaom** [comment]
@Ijaiswalshivam i have fixed it

**Pull request merged**
