### PR TITLE
Bug:after logout it opens directly SigIn  instead of EntryActivity

### PR DESCRIPTION
**Pull request by NitinSigilipelli**
Bug fixed:after logout it opens directly SignIn  instead of EntryActivity

### CODE REVIEW

**Comment by NitinSigilipelli** [comment]
Improved Login  Screen UI 
sample screeshot :
d00ed46b-951a-47eb-a793-6851cd637b64

**Comment by NitinSigilipelli** [comment]
i made two commits into this pr make sure change the label for this pr @Ijaiswalshivam Thank you

**Comment by Ijaiswalshivam** [comment]
@NitinSigilipelli there is one conflict, plz. resolve it

**Comment by NitinSigilipelli** [comment]
yeah it's resolved now ! @Ijaiswalshivam

**Comment by Ijaiswalshivam** [comment]
@NitinSigilipelli logout button, and at sign in page color of border of text message are not visible

**Comment by NitinSigilipelli** [comment]
please check it light theme @Ijaiswalshivam

**Comment by Ijaiswalshivam** [comment]
yes please turn off

**Comment by NitinSigilipelli** [comment]
is verify mail at the time of signup is added or will I do ?

**Comment by NitinSigilipelli** [comment]
> yes please turn off

Ok @Ijaiswalshivam

**Pull request merged**
