### PR TITLE
Improvement in UI of Mobile Authentication screen, chat screen and added search bar functionality

### PR DESCRIPTION
**Pull request by maniyaom**
1. Improved UI of mobile authentication screen
signuppage

2. Added Popup menu on chat screen
popup menu

3. Improved UI of chat screen
chat screen

4. Added Search functionality on main activity
search function

### CODE REVIEW

**Comment by Ijaiswalshivam** [comment]
@maniyaom on signup page with mobile no. "sign up with mail button is not working"

**Comment by maniyaom** [comment]
@Ijaiswalshivam currently i have designed UI of the mobile authentication. I will fix it by tomorrow

**Comment by Ijaiswalshivam** [comment]
@maniyaom please add locate toggle button for location tracking.

**Comment by maniyaom** [comment]
@Ijaiswalshivam toggle button or just a simple button?

**Comment by Ijaiswalshivam** [comment]
Simple

**Pull request merged**
