### PR TITLE
There are some files used in this layout but it is not available in the project

### PR DESCRIPTION
**Pull request by maniyaom**
1. Fixed layout in activity_main.xml.
2. Certain files referenced in this layout are not available in the project. Thus, remove item_message_base.xml, as it causes issues when running the application.

### CODE REVIEW

**Comment by Ijaiswalshivam** [comment]
@maniyaom issue solved now you can see it

**Comment by maniyaom** [comment]
but you have changed that files so that chats are not visible

**Comment by maniyaom** [comment]
@Ijaiswalshivam you have removed some files due to that all the users are not visible

**Comment by Ijaiswalshivam** [comment]
@maniyaom Actually .Json file is of some else...
So correcting in few seconds.

**Pull request closed without merging**
