### PR TITLE
Talk in website

### PR DESCRIPTION
**Pull request by Harish-2003**
added the website for talk-in to make it work kindly change the branch name to ```gh-pages``` and once you changed the branch name after you merged it you can able to see the website at ```Ijaiswalshivam.github.io/Talk-in``` kindly assign the gsoc and level labels to this issue 
closes the issues #295 ```an website for talk in```
_

> _**Warning**_  : don't merge this branch with main branch

### CODE REVIEW

**Comment by Ijaiswalshivam** [comment]
@Harish-2003 please do not delete all files.

**Comment by Harish-2003** [comment]
I have deleted because the branch is for website,so I have only included the files that are related to website

**Comment by Harish-2003** [comment]
Please give me gssoc label and level and change the branch name to gh-pages

**Comment by Harish-2003** [comment]
Give the level and gssoc label to the issue as well

**Pull request merged**
