### PR TITLE
Mobile number authentication added

### PR DESCRIPTION
**Pull request by maniyaom**
#25 Mobile number authentication added
1. Go to Sign Up with mobile number activity
2. Submit your name and mobile number
3. Firebase will verify that you are not a robot 
4. Enter OTP
5. If you have entered correct OTP then you will be redirected to mainactivity.
6. If any user already exist then they will not be able to register with same phone number

### CODE REVIEW

**Comment by maniyaom** [comment]
@Ijaiswalshivam If everything is correct then you can remove my access to the firebase project

**Comment by Ijaiswalshivam** [comment]
@maniyaom currently showing verification failed and also otp not received

**Comment by maniyaom** [comment]
also i have generated SHA-1 in new application so can you check once by clone this project again and then run it?

**Comment by maniyaom** [comment]
https://github.com/Ijaiswalshivam/Talk-In/assets/105499099/e9f342cb-98a2-4af6-af5f-ac79a7ab5dcc

**Comment by Ijaiswalshivam** [comment]
@maniyaom still same

And also requesting you to remove the video for privacy issue

**Comment by maniyaom** [comment]
@Ijaiswalshivam How can i connect with you?

**Comment by Ijaiswalshivam** [comment]
@maniyaom Discord: Shivamjaiswal#2254

**Pull request merged**
