### PR TITLE
feat : Add toast to show the timestamp when the message was sent.

### PR DESCRIPTION
**Pull request by SharmaNishchay**
Added toast to show the timestamp when the message was sent.
Note : The message part is not fully implemented.

### CODE REVIEW

**Comment by SharmaNishchay** [comment]
Need more details for further implementation on this particular feature.

**Comment by Ijaiswalshivam** [comment]
error
please rectify this error

**Comment by SharmaNishchay** [comment]
> error please rectify this error

Can you please tell a way to run that snippet in order to check if it is resolved?

**Comment by Ijaiswalshivam** [comment]
@Vishwajith-Shettigar wait for some time

**Pull request merged**
