### PR TITLE
Track Location of Chatting User Talk-IN

### PR DESCRIPTION
**Pull request by Pranishkafle6175**
User can Track the Location of the User with whom they are chatting .

### CODE REVIEW

**Comment by Ijaiswalshivam** [comment]
@Pranishkafle6175 
Conflicting files
TalkIn/app/src/main/java/com/example/talk_in/ChatActivity.kt
TalkIn/app/src/main/res/layout/activity_chat.xml

And can you please share some screenshots?

**Comment by Pranishkafle6175** [comment]
436423684_2131344557236575_7068982852697229884_n
436598485_7656965634384374_3304180502303800755_n

**Comment by Ijaiswalshivam** [comment]
@Pranishkafle6175 recently we have introduced locate button in each registered user so please delete that icon shift the same action to the new one

**Comment by Pranishkafle6175** [comment]
Done Updated the Map icon to menu

**Comment by Ijaiswalshivam** [comment]
@Pranishkafle6175 please share screenshot

**Comment by Pranishkafle6175** [comment]
What I have done is when user selects the LocateNow a function will call where the location of the sender will be fetched  if he/she has provided location permission and then the user location will be updated in database in node named location and then the receiver location will be fetched and an intent will be passed  with latitude and longitude of both sender and receiver and located in maps.

**Comment by Pranishkafle6175** [comment]
441013674_832502885410810_9179682820757733114_n

**Comment by Ijaiswalshivam** [comment]
@Pranishkafle6175 Due to some uncertain issue, currently I'm not merging it but soon it will be merged as the issue is solved. 
Thank You!

**Comment by Pranishkafle6175** [comment]
Can you tell me the isssue! Is the issue from my side!

**Comment by Ijaiswalshivam** [comment]
no no, not from your side

**Comment by Ijaiswalshivam** [comment]
but please make sure that you worked on the latest committed files.

**Comment by Pranishkafle6175** [comment]
Ohh okay please let me know if there is anything i can do!!

**Comment by Pranishkafle6175** [comment]
Yeah i worked on the latest committed code but since everyone are
committing it may not be the latest when you merge so i request you to
merge fast if possible!

**Comment by Ijaiswalshivam** [comment]
Error In chat activity: Unresolved reference: locateNow,
and try to implement by forking it again so that i can merge this as soon as possible.
fg

**Pull request merged**
