### PR TITLE
Profile Screen added

### PR DESCRIPTION
**Pull request by maniyaom**
1. When user clicks on profile tab it will show current user's profile. log out button is also added there.
2. User can also logout from profile tab
userprofile

3. In chat when user clicks on View Profile app will show receiver user's profile
receiverprofile

### CODE REVIEW

**Comment by Ijaiswalshivam** [comment]
@maniyaom it has some conflicting files.
Conflicting files
TalkIn/app/src/main/java/com/example/talk_in/ChatActivity.kt
TalkIn/app/src/main/java/com/example/talk_in/MainActivity.kt
TalkIn/app/src/main/res/values/strings.xml

please resolve it.

**Comment by Ijaiswalshivam** [comment]
@maniyaom also please add toggle button in about section at top corner for location On/Off by user

**Comment by maniyaom** [comment]
@Ijaiswalshivam conflicts resolved

**Comment by maniyaom** [comment]
> @maniyaom also please add toggle button in about section at top corner for location On/Off by user

@Ijaiswalshivam i will add it but it is there in pop up menu in chat activity.

**Pull request merged**
